package springboot06mybatis.dao;

import springboot06mybatis.pojo.Star;
import springboot06mybatis.utils.ServerResponse;

public interface StarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer starid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated
     */
    int insert(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated
     */
    int insertSelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated
     */
    Star selectByPrimaryKey(Integer starid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Star record);


    Integer selectByUseridAndTaskid(Star star);
}