package springboot06mybatis.pojo;

import java.io.Serializable;

public class Star implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_star.StarId
     *
     * @mbg.generated
     */
    private Integer starid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_star.T_UserId
     *
     * @mbg.generated
     */
    private String tUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_star.T_TaskId
     *
     * @mbg.generated
     */
    private String tTaskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_star
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_star.StarId
     *
     * @return the value of t_star.StarId
     *
     * @mbg.generated
     */
    public Integer getStarid() {
        return starid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_star.StarId
     *
     * @param starid the value for t_star.StarId
     *
     * @mbg.generated
     */
    public void setStarid(Integer starid) {
        this.starid = starid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_star.T_UserId
     *
     * @return the value of t_star.T_UserId
     *
     * @mbg.generated
     */
    public String gettUserid() {
        return tUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_star.T_UserId
     *
     * @param tUserid the value for t_star.T_UserId
     *
     * @mbg.generated
     */
    public void settUserid(String tUserid) {
        this.tUserid = tUserid == null ? null : tUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_star.T_TaskId
     *
     * @return the value of t_star.T_TaskId
     *
     * @mbg.generated
     */
    public String gettTaskid() {
        return tTaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_star.T_TaskId
     *
     * @param tTaskid the value for t_star.T_TaskId
     *
     * @mbg.generated
     */
    public void settTaskid(String tTaskid) {
        this.tTaskid = tTaskid == null ? null : tTaskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", starid=").append(starid);
        sb.append(", tUserid=").append(tUserid);
        sb.append(", tTaskid=").append(tTaskid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}