package springboot06mybatis.pojo;

import java.io.Serializable;

public class TaskIMG implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taskimg.T_ImgId
     *
     * @mbg.generated
     */
    private Integer tImgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taskimg.T_TaskId
     *
     * @mbg.generated
     */
    private Integer tTaskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taskimg.T_ImgURL
     *
     * @mbg.generated
     */
    private String tImgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_taskimg
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taskimg.T_ImgId
     *
     * @return the value of t_taskimg.T_ImgId
     *
     * @mbg.generated
     */
    public Integer gettImgid() {
        return tImgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taskimg.T_ImgId
     *
     * @param tImgid the value for t_taskimg.T_ImgId
     *
     * @mbg.generated
     */
    public void settImgid(Integer tImgid) {
        this.tImgid = tImgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taskimg.T_TaskId
     *
     * @return the value of t_taskimg.T_TaskId
     *
     * @mbg.generated
     */
    public Integer gettTaskid() {
        return tTaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taskimg.T_TaskId
     *
     * @param tTaskid the value for t_taskimg.T_TaskId
     *
     * @mbg.generated
     */
    public void settTaskid(Integer tTaskid) {
        this.tTaskid = tTaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taskimg.T_ImgURL
     *
     * @return the value of t_taskimg.T_ImgURL
     *
     * @mbg.generated
     */
    public String gettImgurl() {
        return tImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taskimg.T_ImgURL
     *
     * @param tImgurl the value for t_taskimg.T_ImgURL
     *
     * @mbg.generated
     */
    public void settImgurl(String tImgurl) {
        this.tImgurl = tImgurl == null ? null : tImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taskimg
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tImgid=").append(tImgid);
        sb.append(", tTaskid=").append(tTaskid);
        sb.append(", tImgurl=").append(tImgurl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}